import type { Metadata } from "next";
import {
  Geist,
  Geist_Mono,
  // Plus_Jakarta_Sans,
  // Reenie_Beanie,
  // Roboto,
  // Bricolage_Grotesque,
  // Anton,
  // Playfair_Display,
  // Poetsen_One,
  // Lora,
  // Russo_One,
  // Jersey_15,
  // Original_Surfer,
  // Inter,
  // Poppins,
  // Literata,
  // Manrope,
} from "next/font/google";

import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";

// const jakarta = Plus_Jakarta_Sans({
//   variable: "--font-jakarta",
//   subsets: ["latin"],
// });

// const reenie = Reenie_Beanie({
//   variable: "--font-reenie",
//   weight: "400",
//   subsets: ["latin"],
// });

// const roboto = Roboto({
//   variable: "--font-roboto",
//   subsets: ["latin"],
// });

// const bricolage = Bricolage_Grotesque({
//   variable: "--font-bricolage",
//   subsets: ["latin"],
// });

// const anton = Anton({
//   variable: "--font-anton",
//   weight: "400",
//   subsets: ["latin"],
// });

// const playfair = Playfair_Display({
//   variable: "--font-playfair",
//   subsets: ["latin"],
// });

// const poetsen = Poetsen_One({
//   variable: "--font-poetsen",
//   weight: "400",
//   subsets: ["latin"],
// });

// const lora = Lora({
//   variable: "--font-lora",
//   subsets: ["latin"],
// });

// const russo = Russo_One({
//   variable: "--font-russo",
//   weight: "400",
//   subsets: ["latin"],
// });

// const jersey = Jersey_15({
//   variable: "--font-jersey",
//   weight: "400",
//   subsets: ["latin"],
// });

// const surfer = Original_Surfer({
//   variable: "--font-surfer",
//   weight: "400",
//   subsets: ["latin"],
// });

// const inter = Inter({
//   variable: "--font-inter",
//   subsets: ["latin"],
// });

// const poppins = Poppins({
//   variable: "--font-poppins",
//   weight: ["400", "500", "600", "700"],
//   subsets: ["latin"],
// });

// const literata = Literata({
//   variable: "--font-literata",
//   subsets: ["latin"],
// });

// const manrope = Manrope({
//   variable: "--font-manrope",
//   subsets: ["latin"],
// });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// ${jakarta.variable}
// ${reenie.variable}
// ${roboto.variable}
// ${bricolage.variable}
// ${anton.variable}
//     ${playfair.variable}
// ${poetsen.variable}
// ${lora.variable}
// ${russo.variable}
// ${jersey.variable}
// ${surfer.variable}
// ${inter.variable}
// ${poppins.variable}
// ${literata.variable}
// ${manrope.variable}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable}
    ${geistMono.variable}

    h-full antialiased`}
      suppressHydrationWarning
    >
      <body className="min-h-full flex flex-col">
        <ThemeProvider>
          <div></div>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
